import Layout from "../components/MainLayout";



export default function Ligislation() {
    return (
        <Layout>
        <div className="main-other-pages">
            <div>
            <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '13.999999999999998pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Pour nous il est impératif que chaque partenaire autocariste respecte scrupuleusement la législation dont voici un résumé dans les grandes lignes :</span></p>
                  <p><br /></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La durée maximum de conduite continue</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                   
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La conduite continue ne doit pas dépasser 4h30 durant la journée et 3h pendant la nuit.</span></p>
                  
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Les déplacements de nuit de 22:00 heures à 6:00 heures exécutés</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>par un seul chauffeur ne peuvent pas avoir une durée de conduite</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>de plus de 3 heures.</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>En cas de dépassement de temps, la conduite doit s’effectuer en</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>équipage double.</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Au delà un arrêt de 45mn doit être respecté, éventuellement fractionné en deux périodes, la première étant alors de 15mn et la seconde de 30mn.</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La durée maximum de conduite journalière</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Un chauffeur ne doit pas dépasser 9h de conduite journalière.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La durée de conduite peut être portée à 10h maximum deux fois par semaine et par conducteur.</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Temps de repos journalier</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Le repos journalier normal est fixé à 11 heures consécutives, il peut être réduit et passe alors à 9 heures au maximum 3 fois par semaine.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Si le fractionnement du repos est fait en deux périodes celui ci peut aller jusqu' à 12h dont une de 3h et 9h consécutives minimum.</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>L'amplitude et son dépassement</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>L'amplitude de la journée de travail d'un conducteur est la période comprise entre le début et la fin de sa journée de travail.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Il ne faut pas oublier que le conducteur commence sa journée avant la prise en charge, et qu’il la termine après la dépose au retour.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La durée maximale de la conduite journalière est de 9 heures. Elle</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>peut toutefois se porter à 10 heures deux fois par semaine.</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Au delà de 14h d'amplitude et jusqu'à 20h il est donc nécessaire de mettre à disposition un deuxième chauffeur.</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp; &nbsp; &nbsp; &nbsp; En cas de double équipage, chaque conducteur doit bénéficier d’au moins 9 heures consécutives de repos au cours de chaque période de 30 heures.</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Déplacement du repos hebdomadaire</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Le repos est applicable après 6 jours consécutifs de travail.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Dans le transport de personnes, une période de 12 jours consécutifs</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>sans repos hebdomadaire est possible en cas de course hors du pays</span></p>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>pour autant qu’il s’agisse d’une seule et même course.</span></p>
                  <ul style={{marginTop: '0px', marginBottom: '0px', paddingInlineStart: '48px'}}>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>La durée de repos hebdomadaire doit être égale à 45h consécutives.</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Il est possible de prendre une semaine sur deux un repos réduit à 24h sous condition de rattrapage du repos réduit</span></p>
                    </p>
                    <p aria-level={1} dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri, sans-serif', fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
                      <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '12pt', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>L'obligation d'un repos de 45h se fait au moins une fois tous les 15 jours.</span></p>
                    </p>
                  </ul>
                  <p dir="ltr" style={{lineHeight: '1.3800000000000001', textAlign: 'center', marginTop: '0pt', marginBottom: '10pt'}}><span style={{fontSize: '20pt', fontFamily: 'Calibri, sans-serif', fontWeight: 700, fontStyle: 'italic', fontVariantLigatures: 'normal', fontVariantEastAsian: 'normal', fontVariantPosition: 'normal', textDecoration: 'underline', textDecorationSkip: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>ExpoTours.ch</span></p>
                  <p><br /></p>
                  <p><br /></p>
                </div>
            </div>
        </Layout>
    )
}